version: '3.8'

services:
  postgres:
    image: postgres:11.10-alpine
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  # For unit test only
  postgres-test:
    image: postgres:11.10-alpine
    restart: always
    ports:
      - ${POSTGRES_TEST_PORT}:5432
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  redis:
    image: redis:6.0.9-alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379

  redis-test:
    image: redis:6.0.9-alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_TEST_PORT}:6379

  server:
    build: .
    depends_on:
      - postgres
      - redis
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./data/coverage:/pl-server/data/coverage
      - ./data/report:/pl-server/data/report
    environment:
      - PORT
      - ENABLE_CORS
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT
      - POSTGRES_TEST_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - REDIS_HOST=redis
      - REDIS_PORT
      - REDIS_TEST_PORT
      - REDIS_PASSWORD
      - P_PUBLIC_KEY
      - S_PUBLIC_KEY
      - S_PRIVATE_KEY
      - U_PUBLIC_KEY
